web:
  build: .
  ports:
    - "8000:80"
  links:
    - db
  environment:
    DATABASE_HOST: db
    DATABASE_PORT: 3306
    DATABASE_NAME: drupal
    DATABASE_USER: root
    DATABASE_PASSWORD: pass
db:
  image: mysql
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: pass
